server:
  port: 8006

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/base_framework?serverTimezone=UTC&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf8
    username: root
    password:
  resources:
    static-locations: classpath:/templates/,classpath:/static/

mybatis-plus:
  mapper-locations: classpath:com/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #\u5F00\u542F\u9A7C\u5CF0
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl